# Generated by Django 4.2 on 2025-09-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentchoice',
            name='allocated_course',
        ),
        migrations.RemoveField(
            model_name='studentchoice',
            name='student',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='StudentChoice',
        ),
    ]
