# Generated by Django 4.2 on 2025-09-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('ALLOCATED', 'Allocated'), ('CONFIRMED', 'Confirmed'), ('WITHDRAWN', 'Withdrawn')], default='ALLOCATED', max_length=20),
        ),
    ]
