# Generated by Django 4.2 on 2025-09-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('degree_type', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.E.', 'Bachelor of Engineering'), ('B.Sc', 'Bachelor of Science'), ('M.Tech', 'Master of Technology'), ('M.E.', 'Master of Engineering'), ('M.Sc', 'Master of Science')], max_length=50)),
                ('duration_years', models.IntegerField(default=4)),
                ('total_seats', models.IntegerField()),
                ('seats_filled', models.IntegerField(default=0)),
                ('fee_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.collegeprofile')),
            ],
            options={
                'ordering': ['college', 'course_name'],
                'unique_together': {('college', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('finalized', 'Finalized'), ('upgraded', 'Upgraded'), ('withdrawn', 'Withdrawn')], default='allocated', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-round_number', 'allocated_at'],
                'unique_together': {('student', 'round_number')},
            },
        ),
    ]
