# Generated by Django 4.2 on 2025-09-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
    ]
