# Generated by Django 4.2 on 2025-09-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='round_number',
        ),
    ]
